default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres


development:
  <<: *default
  database: my_app_development
test:
  <<: *default
  database: my_app_test
